steps:
  - name: "curl"
    template: "curl"
    option:
      url: "https://www.yahoo.co.jp/"
      method: "GET"
      expect:
        status: 200
        body: '{"sample": "aaa"}'
  - name: "curl"
    template: "curl"
    option:
      url: "https://www.yahoo.co.jp/"
      method: "GET"
      expect:
        equal: "https://www.yahoo.co.jp/"
        status: 200
        body: "@file=./sample.yaml"
#  - name: "html"
#    template: "html"
#    option:
#      url: "https://www.yahoo.co.jp/"
      #screenshot:
      #  waitSec: 1
#      coreWebVital:
#        waitSec: 1
